stages:
    - build
    - deploy

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "web"

cache:
    key:
        files:
            - package-lock.json
    paths:
        - node_modules/

build:
    stage: build
    tags:
        - site-ll
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - dist/

deploy:
    stage: deploy
    tags:
        - site-ll
    script:
        - cp -r dist/ /appli/website
