pages:
    image: node:lts-alpine
    tags:
        - gitlab-ci-learninglab-4
    before_script:
        - npm ci --cache .npm --prefer-offline
    script:
        - NUXT_APP_BASE_URL=/site-ll/ npm run generate
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - .npm/
    artifacts:
        paths:
            - .output/public
    publish: .output/public
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
