# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Inria Learning Lab
site_url: https://learninglab.gitlabpages.inria.fr/site-ll
use_directory_urls: false
extra_css:
    - stylesheets/extra.css
plugins:
    - blog:
          blog_dir: blog
    - blog:
          blog_dir: ePoc
          blog_toc: false
          post_url_format: "{slug}"
          archive: false
    - blog:
          blog_dir: mooc
          blog_toc: false
          post_url_format: "{slug}"
          archive: false
    - search
    - awesome-pages
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
theme:
    logo: assets/logo/ill-logo.png
    name: material
    language: fr
    features:
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
        - scheme: default
          primary: custom
          accent: amber
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: custom
          accent: amber
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

copyright: '
    <div style="display:flex;justify-content:center;align-items:center;gap:1rem">
    <a href="https://inria.fr/fr">
    <img alt="logo Inria" src="/site-ll/assets/logo/inria-logo.svg" style="width: 150px;height: auto;border-radius: 4px">
    </a>
    <a href="mailto:ill-contact@inria.fr" style="display:flex;align-items:center;gap:.3rem;font-size:.7rem">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mail"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
    ill-contact@inria.fr
    </a>
    </div>
    '
