map $request_uri $redirect_url {
    /cours /moocs;
    /en/cours /en/moocs;
    /qui-sommes-nous /team;
    /en/qui-sommes-nous /en/team;

    /contact mailto:ill-contact@inria.fr;
    /en/contact mailto:ill-contact@inria.fr;
}
